# Generated by Django 3.1.6 on 2021-02-23 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_bid_comment_listing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='imageurl',
            field=models.URLField(blank=True, max_length=400, null=True),
        ),
    ]
