# Generated by Django 3.1.6 on 2021-02-24 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_auto_20210224_0521'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='initialprice',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
