# Generated by Django 3.1.6 on 2021-02-24 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_listing_initialprice'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='commentdate',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
