# Generated by Django 3.1.6 on 2021-02-25 23:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_auto_20210226_0451'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='catagory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='listings', to='auctions.catagory'),
        ),
    ]
