# Generated by Django 3.1.6 on 2021-02-26 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0012_auto_20210226_1949'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='currentprice',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=10, null=True),
        ),
    ]
